Require dali2-usd-loader only if OpenUSD library found
dalihub/dali-test pull request #66
Opened 2024-11-15 04:09 UTC by hinohie

Let we try to require dali2-usd-loader only if it is exist.

2025-03-07 09:06 UTC, hrdisaac approved these changes

2025-03-07 14:56 UTC, adeelkazmi requested changes

2025-03-07 14:56 UTC, adeelkazmi commented on build/tizen/CMakeLists.txt
> +OPTION(USD_LOADER_ENABLED "Whether dali-usd-loader is enabled." OFF)
No need having it as an option as it's overridden later on anyway. May as well just use a variable.

2025-03-11 03:47 UTC, hinohie commented on build/tizen/CMakeLists.txt
> +OPTION(USD_LOADER_ENABLED "Whether dali-usd-loader is enabled." OFF)
Thank you for your reply. Fix done.

2025-03-13 10:33 UTC, adeelkazmi approved these changes

2025-03-13 10:33 UTC, merged